version: '3.4'

services:
    mssql:
        container_name: LocalwebshopDB
        hostname: sql-webshopDB
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Wachtwoord1!
            - MSSQL_PID=Express
        ports:
            - '1433:1433'
        image: 'mcr.microsoft.com/mssql/server:latest'