version: '3.4'

services:
    mssql:
        container_name: webshopDB
        hostname: sql-webshopDB
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Wachtwoord1!
            - MSSQL_PID=Express
        ports:
            - '1433:1433'
        image: 'mcr.microsoft.com/mssql/server:latest'

    webshopapi:
      image: ${DOCKER_REGISTRY-}webshopapi
      ports:
        - '8080:80'
        - '8081:443'
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+8081;http://+8080
        - ASPNETCORE_HTTPS_PORT:"8081"
        - ASPNETCORE_Kestrel__Certificates__Default__Password=Wachtwoord1!
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/WebshopAPI.pfx
      volumes:
        - ~/.aspnet/https:/https:ro
      build:
        context: .
        dockerfile: WebshopAPI/Dockerfile

