// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebshopAPI.Context;

#nullable disable

namespace WebshopAPI.Migrations
{
    [DbContext(typeof(WebshopContext))]
    partial class WebshopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebshopAPI.Models.Products", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime?>("AvailableSince")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Property1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property14")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property16")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property17")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property18")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property19")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property20")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property21")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property22")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property23")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property24")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property25")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property9")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
